global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
- job_name: redpanda-a
  static_configs:
  - targets:
    - redpanda-a:9644
  metrics_path: /public_metrics
- job_name: redpanda-a-internal
  static_configs:
  - targets:
    - redpanda-a:9644
  metrics_path: /metrics
- job_name: connect
  static_configs:
  - targets:
    - connect:9010
  metrics_path: /